// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: config.proto

package chitanda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psk           string                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Fallback      string                 `protobuf:"bytes,3,opt,name=fallback,proto3" json:"fallback,omitempty"`
	StrictSni     string                 `protobuf:"bytes,4,opt,name=strict_sni,json=strictSni,proto3" json:"strict_sni,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	ServerId      string                 `protobuf:"bytes,6,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ReplayFile    string                 `protobuf:"bytes,7,opt,name=replay_file,json=replayFile,proto3" json:"replay_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *InboundConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *InboundConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InboundConfig) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *InboundConfig) GetStrictSni() string {
	if x != nil {
		return x.StrictSni
	}
	return ""
}

func (x *InboundConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *InboundConfig) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InboundConfig) GetReplayFile() string {
	if x != nil {
		return x.ReplayFile
	}
	return ""
}

type OutboundConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Psk           string                 `protobuf:"bytes,3,opt,name=psk,proto3" json:"psk,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	PoolSize      int32                  `protobuf:"varint,6,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	ServerId      string                 `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *OutboundConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *OutboundConfig) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

func (x *OutboundConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutboundConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *OutboundConfig) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *OutboundConfig) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x13xray.proxy.chitanda\"\x8e\x01\n" +
	"\rInboundConfig\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\tR\x03psk\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bfallback\x18\x03 \x01(\tR\bfallback\x12\x1d\n" +
	"\n" +
	"strict_sni\x18\x04 \x01(\tR\tstrictSni\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\"\xaa\x01\n" +
	"\x0eOutboundConfig\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03psk\x18\x03 \x01(\tR\x03psk\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12\x1b\n" +
	"\tpool_size\x18\x06 \x01(\x05R\bpoolSizeB[\n" +
	"\x17com.xray.proxy.chitandaP\x01Z(github.com/xtls/xray-core/proxy/chitanda\xaa\x02\x13Xray.Proxy.Chitandab\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_proto_goTypes = []any{
	(*InboundConfig)(nil),  // 0: xray.proxy.chitanda.InboundConfig
	(*OutboundConfig)(nil), // 1: xray.proxy.chitanda.OutboundConfig
}
var file_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
